AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  backmasking

Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  CreateBackmaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backmasking_function/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
      Events:
        CreateBackmask:
          Type: Api
          Properties:
            Path: /backmask
            Method: post
      Layers:
        - !Ref FFMPEGLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - polly:SynthesizeSpeech
              Resource: "*"

  FFMPEGLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pydub-ffmpeg
      Description: Dependencies for backmasking service
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.8
      LicenseInfo: "https://ffmpeg.org/legal.html"
Outputs:
  BackmaskApi:
    Description: "API Gateway endpoint URL for Prod stage for Create Activity Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/backmask/"
